spring:
  application:
    name: customerService
  profiles:
    active: dev
server:
  port: ${app_port}
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8900/eureka
    fetch-registry: true
