server:
  port: 8097

spring:
  profiles:
    include: db
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
